# Generated by Django 3.2.6 on 2021-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_thumbnail_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_image',
            field=models.ImageField(default='blog.png', upload_to='blog_images/'),
        ),
    ]
