# Generated by Django 3.2.4 on 2021-08-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('title', models.CharField(choices=[('Professor', 'Professor'), ('Doctor', 'Doctor'), ('Pharm Doctor', 'Pharm Doctor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=12)),
                ('year_of_graduation', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(help_text='If Nigeria is chosen', max_length=10)),
                ('day_of_birth', models.CharField(max_length=2)),
                ('month_of_birth', models.CharField(max_length=2)),
                ('profession', models.CharField(max_length=20)),
                ('ministry_group', models.CharField(help_text='enter ministry group joined, if you joined any', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
