# Generated by Django 3.2.4 on 2021-08-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day_of_birth',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ministry_group',
            field=models.CharField(blank=True, help_text='enter ministry group joined, if you joined any', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='month_of_birth',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text='If Nigeria is chosen', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_graduation',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
