# Generated by Django 3.2.4 on 2021-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
