# Generated by Django 3.2.6 on 2021-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210819_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Doctor', 'Doctor'), ('Pharm Doctor', 'Pharm Doctor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=12),
        ),
    ]
