# Generated by Django 3.2.6 on 2021-08-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
