# Generated by Django 3.2.6 on 2021-08-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Doctor', 'Doctor'), ('Pharm Doctor', 'Pharm Doctor'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Rev', 'Rev')], max_length=12),
        ),
    ]
