# Generated by Django 3.2.6 on 2021-08-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
