# Generated by Django 3.2.6 on 2021-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizhub',
            name='locaton',
        ),
        migrations.AddField(
            model_name='bizhub',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bizhub',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bizhub',
            name='business_sector',
            field=models.CharField(choices=[('Law', 'Law'), ('Software Development', 'Software Development'), ('Health Care', 'Health Care'), ('Accounting', 'Accounting'), ('Engineering', 'Engineering'), ('Ecommerce', 'Ecommerce'), ('Design', 'Design'), ('ICT', 'ICT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='bizhub',
            name='description',
            field=models.TextField(blank=True, help_text='Give a little description of your business'),
        ),
    ]
