# Generated by Django 3.2.6 on 2021-08-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizhub', '0002_auto_20210820_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizhub',
            name='business_sector',
            field=models.CharField(choices=[('Law', 'Law'), ('Software Development', 'Software Development'), ('Health Care', 'Health Care'), ('Accounting', 'Accounting'), ('Engineering', 'Engineering'), ('Ecommerce', 'Ecommerce'), ('Design', 'Design'), ('Ict', 'Ict')], max_length=200),
        ),
    ]
